
name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci
      
      - name: Build App
        run: npm run build
      
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v3

      - name: Build and Push Docker Image
        run: gcloud builds submit --tag REGION-docker.pkg.dev/crucial-ray-490222-n3/notely-ar-repo/notely:TAG .